CCFLAGS = -Wall -Werror -Wextra

Task1: obj obj/Task1.o
	g++ $(CCFLAGS) --std=c++17 -o Task1 obj/Task1.o
	chmod +x Task1

Task2: obj obj/Task2.o
	g++ $(CCFLAGS) --std=c++17 -o Task2 obj/Task2.o
	chmod +x Task2

Task3: obj obj/Task3.o
	g++ $(CCFLAGS) --std=c++17 -o Task3 obj/Task3.o
	chmod +x Task3

Task4: obj obj/Task4.o
	g++ $(CCFLAGS) --std=c++17 -o Task4 obj/Task4.o
	chmod +x Task4

Task5: obj obj/Task5.o
	g++ $(CCFLAGS) --std=c++17 -o Task5 obj/Task5.o
	chmod +x Task5

Task6: obj obj/Task6.o
	g++ $(CCFLAGS) --std=c++17 -o Task6 obj/Task6.o
	chmod +x Task6

Task7: obj obj/Task7.o
	g++ $(CCFLAGS) --std=c++17 -o Task7 obj/Task7.o
	chmod +x Task7

Task8: obj obj/Task8.o
	g++ $(CCFLAGS) --std=c++17 -o Task8 obj/Task8.o
	chmod +x Task8

Task9: obj obj/Task9.o
	g++ $(CCFLAGS) --std=c++17 -o Task9 obj/Task9.o
	chmod +x Task9

Task10: obj obj/Task10.o
	g++ $(CCFLAGS) --std=c++17 -o Task10 obj/Task10.o
	chmod +x Task10

Task11: obj obj/Task11.o
	g++ $(CCFLAGS) --std=c++17 -o Task11 obj/Task11.o
	chmod +x Task11

obj:
	mkdir obj

obj/Task1.o: src/Task1.cpp
	g++ $(CCFLAGS) --std=c++17 -o obj/Task1.o -c src/Task1.cpp

obj/Task2.o: src/Task2.cpp
	g++ $(CCFLAGS) --std=c++17 -o obj/Task2.o -c src/Task2.cpp

obj/Task3.o: src/Task3.cpp
	g++ $(CCFLAGS) --std=c++17 -o obj/Task3.o -c src/Task3.cpp

obj/Task4.o: src/Task4.cpp
	g++ $(CCFLAGS) --std=c++17 -o obj/Task4.o -c src/Task4.cpp

obj/Task5.o: src/Task5.cpp
	g++ $(CCFLAGS) --std=c++17 -o obj/Task5.o -c src/Task5.cpp

obj/Task6.o: src/Task6.cpp
	g++ $(CCFLAGS) --std=c++17 -o obj/Task6.o -c src/Task6.cpp

obj/Task7.o: src/Task7.cpp
	g++ $(CCFLAGS) --std=c++17 -o obj/Task7.o -c src/Task7.cpp

obj/Task8.o: src/Task8.cpp
	g++ $(CCFLAGS) --std=c++17 -o obj/Task8.o -c src/Task8.cpp

obj/Task9.o: src/Task9.cpp
	g++ $(CCFLAGS) --std=c++17 -o obj/Task9.o -c src/Task9.cpp

obj/Task10.o: src/Task10.cpp
	g++ $(CCFLAGS) --std=c++17 -o obj/Task10.o -c src/Task10.cpp

obj/Task11.o: src/Task11.cpp
	g++ $(CCFLAGS) --std=c++17 -o obj/Task11.o -c src/Task11.cpp

clean:
	rm -r obj
	rm Task1
	rm Task2
	rm Task3
	rm Task4
	rm Task5
	rm Task6
	rm Task7
	rm Task8
	rm Task9
	rm Task10




